apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data
    server: 192.168.1.115
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
