apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecommerce-be
  name: ecommerce-be-deployment
  namespace: ecommerce
spec:
  replicas: 1
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: ecommerce-be
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecommerce-be
      namespace: ecommerce
    spec:
      containers:
        - image: vietquoc2408/k8s-ecommerce-be
          imagePullPolicy: Always
          name: ecommerce-be
          ports:
            - containerPort: 80
              name: tcp
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-be-service
  namespace: ecommerce
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ecommerce-be
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-be-ingress
  namespace: ecommerce
spec:
  ingressClassName: nginx
  rules:
    - host: api-ecommerce.vietquoc.vn
      http:
        paths:
          - backend:
              service:
                name: ecommerce-be-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
