apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ecommerce-be-autoscaling
  namespace: ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: ecommerce-be-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
